name: Build PrivateGPT

on:
  push:
    #branches:
    #  - 'main'
    paths:
      - '**'
      - '!README.md'
  #schedule:
    # cron: 'min hour day month weekday'
    #- cron: '0 4 * * 3' # every wednesday on 04:00
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'run action manually'

jobs:
  multi:
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Tag
        id: tag
        run: |
          docker build -t fireblzr/privategpt:latest --build-arg HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }} ./
          CONTAINER_ID=$(docker create fireblzr/privategpt:latest)
          docker cp "${CONTAINER_ID}:/VERSION" VERSION
          VERSION=$(cat VERSION | grep privategpt | cut -d= -f2 | head -n 1)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}
          tags: |
            fireblzr/privategpt:latest
            fireblzr/privategpt:${{ steps.tag.outputs.VERSION }}
